import { PokemonType } from "@/types/card";

export const TYPE_COLORS: Record<PokemonType, { bg: string; text: string; gradient: string; border: string; badge: string; energy: string }> = {
  fire: {
    bg: "bg-orange-50",
    text: "text-orange-900",
    gradient: "from-red-400 via-orange-300 to-yellow-200",
    border: "border-orange-400",
    badge: "bg-orange-500",
    energy: "🔥",
  },
  water: {
    bg: "bg-blue-50",
    text: "text-blue-900",
    gradient: "from-blue-500 via-blue-300 to-cyan-200",
    border: "border-blue-400",
    badge: "bg-blue-500",
    energy: "💧",
  },
  grass: {
    bg: "bg-green-50",
    text: "text-green-900",
    gradient: "from-green-500 via-green-300 to-lime-200",
    border: "border-green-400",
    badge: "bg-green-500",
    energy: "🌿",
  },
  electric: {
    bg: "bg-yellow-50",
    text: "text-yellow-900",
    gradient: "from-yellow-400 via-yellow-200 to-amber-100",
    border: "border-yellow-400",
    badge: "bg-yellow-500",
    energy: "⚡",
  },
  psychic: {
    bg: "bg-purple-50",
    text: "text-purple-900",
    gradient: "from-purple-400 via-pink-300 to-purple-200",
    border: "border-purple-400",
    badge: "bg-purple-500",
    energy: "🔮",
  },
  fighting: {
    bg: "bg-red-50",
    text: "text-red-900",
    gradient: "from-red-500 via-red-300 to-orange-200",
    border: "border-red-400",
    badge: "bg-red-600",
    energy: "👊",
  },
  dark: {
    bg: "bg-gray-100",
    text: "text-gray-900",
    gradient: "from-gray-700 via-gray-500 to-gray-300",
    border: "border-gray-600",
    badge: "bg-gray-700",
    energy: "🌑",
  },
  steel: {
    bg: "bg-slate-50",
    text: "text-slate-900",
    gradient: "from-slate-400 via-slate-300 to-slate-200",
    border: "border-slate-400",
    badge: "bg-slate-500",
    energy: "⚙️",
  },
  dragon: {
    bg: "bg-indigo-50",
    text: "text-indigo-900",
    gradient: "from-indigo-500 via-purple-400 to-indigo-300",
    border: "border-indigo-500",
    badge: "bg-indigo-600",
    energy: "🐉",
  },
  fairy: {
    bg: "bg-pink-50",
    text: "text-pink-900",
    gradient: "from-pink-400 via-pink-200 to-rose-100",
    border: "border-pink-400",
    badge: "bg-pink-500",
    energy: "✨",
  },
  normal: {
    bg: "bg-stone-50",
    text: "text-stone-900",
    gradient: "from-stone-300 via-stone-200 to-stone-100",
    border: "border-stone-400",
    badge: "bg-stone-500",
    energy: "⭐",
  },
  ghost: {
    bg: "bg-violet-50",
    text: "text-violet-900",
    gradient: "from-violet-500 via-purple-400 to-violet-300",
    border: "border-violet-500",
    badge: "bg-violet-600",
    energy: "👻",
  },
  ice: {
    bg: "bg-cyan-50",
    text: "text-cyan-900",
    gradient: "from-cyan-300 via-sky-200 to-blue-100",
    border: "border-cyan-400",
    badge: "bg-cyan-500",
    energy: "❄️",
  },
  poison: {
    bg: "bg-fuchsia-50",
    text: "text-fuchsia-900",
    gradient: "from-fuchsia-500 via-purple-400 to-fuchsia-300",
    border: "border-fuchsia-400",
    badge: "bg-fuchsia-600",
    energy: "☠️",
  },
  ground: {
    bg: "bg-amber-50",
    text: "text-amber-900",
    gradient: "from-amber-500 via-yellow-400 to-amber-200",
    border: "border-amber-500",
    badge: "bg-amber-600",
    energy: "🌍",
  },
  bug: {
    bg: "bg-lime-50",
    text: "text-lime-900",
    gradient: "from-lime-400 via-green-300 to-lime-200",
    border: "border-lime-400",
    badge: "bg-lime-600",
    energy: "🐛",
  },
  rock: {
    bg: "bg-amber-50",
    text: "text-amber-900",
    gradient: "from-amber-600 via-yellow-500 to-amber-300",
    border: "border-amber-500",
    badge: "bg-amber-700",
    energy: "🪨",
  },
  flying: {
    bg: "bg-sky-50",
    text: "text-sky-900",
    gradient: "from-sky-300 via-blue-200 to-indigo-100",
    border: "border-sky-400",
    badge: "bg-sky-500",
    energy: "🕊️",
  },
};

export const RARITY_STYLES = {
  common: "ring-2 ring-stone-300",
  uncommon: "ring-2 ring-green-400",
  rare: "ring-2 ring-blue-500 shadow-lg shadow-blue-200",
  holo: "ring-3 ring-purple-500 shadow-xl shadow-purple-300",
  legendary: "ring-4 ring-yellow-400 shadow-2xl shadow-yellow-300",
};
